// Server Entry Point - Updated for DB Fix
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import dotenv from 'dotenv';
import swaggerUi from 'swagger-ui-express';
import { createServer } from 'http';
import path from 'path';
import { fileURLToPath } from 'url';
import { connectDatabase } from './config/database.js';
import { config } from './config/env.js';
import mongoose from 'mongoose';
import { errorHandler } from './middleware/errorHandler.js';
import { logger } from './utils/logger.js';
import { toApiError } from './errors/ApiError.js';
// Rate limiters removed from global scope if unused, or keep if needed later. But build fails.
// Assuming they are used in app.use lines not shown.
// If TS says they are unused, they really are unused.
// I will check if I can just remove the line.
import { performanceMonitor } from './middleware/performanceMonitor.js';
import { swaggerSpec } from './config/swagger.js';
import { apiVersioning } from './middleware/apiVersioning.js';
import { redisService } from './services/redis.service.js';
import { queueService } from './services/queue.service.js';
import { securityHeaders } from './middleware/securityHeaders.js';
import { requestTimeout } from './middleware/timeout.js';
import { webSocketService } from './services/websocket.service.js';
import { forceJsonResponse } from './middleware/forceJsonResponse.js';
import { offlineModeMiddleware } from './middleware/offlineMode.js';

// Routes
import { loadRoutes } from './utils/routeLoader.js';
import { maintenanceModeMiddleware } from './middleware/maintenanceMode.js';

dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Initialize Sentry error tracking (before other imports that might throw)
try {
  const { initSentry } = await import('./services/monitoring/sentry.js');
  initSentry();
} catch (error: unknown) {
  logger.warn('Sentry initialization failed (optional):', toApiError(error).message);
}

const app = express();
const httpServer = createServer(app);
const PORT = config.port;

// Trust proxy to get correct IP addresses (important for rate limiting)
// In development, this helps detect localhost correctly
app.set('trust proxy', true);

// Middleware
app.use(helmet());
app.use(securityHeaders); // Additional security headers

// Security Headers for WebContainer Support (SharedArrayBuffer)
// app.use((req, res, next) => {
//   res.setHeader('Cross-Origin-Embedder-Policy', 'require-corp');
//   res.setHeader('Cross-Origin-Opener-Policy', 'same-origin');
//   next();
// });

// CORS Configuration - configurable per environment
app.use(cors({
  origin: (origin, callback) => {
    // Allow requests with no origin (mobile apps, curl, Postman, etc.)
    if (!origin) {
      return callback(null, true);
    }

    // Check if origin is in allowed list
    if (origin) {
      logger.info(`[CORS DEBUG] Request Origin: ${origin}, Is Allowed: ${config.corsOrigins.includes(origin)}`);
    }

    if (config.corsOrigins.includes(origin)) {
      callback(null, true);
    } else {
      // In development, restrict to localhost only
      if (config.nodeEnv === 'development') {
        const isLocalhost = origin.match(/^http:\/\/localhost:\d+$/) || origin.match(/^http:\/\/127\.0\.0\.1:\d+$/);
        if (isLocalhost) {
          logger.warn(`CORS: Origin ${origin} not in allowed list, but allowing (localhost)`);
          callback(null, true);
        } else {
          logger.warn(`CORS: Blocked external request in dev: ${origin}`);
          callback(new Error('Not allowed by CORS (Dev Mode Restricted)'));
        }
      } else {
        // In production, reject unauthorized origins
        logger.warn(`CORS: Blocked request from unauthorized origin: ${origin}`);
        callback(new Error('Not allowed by CORS'));
      }
    }
  },
  credentials: config.corsCredentials,
  methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
  allowedHeaders: ['Content-Type', 'Authorization', 'x-user-id', 'bypass-tunnel-reminder', 'ngrok-skip-browser-warning'],
  exposedHeaders: ['Content-Range', 'X-Total-Count'],
  maxAge: 86400 // 24 hours
}));
app.use(express.json({ limit: '10mb' }));
app.use(express.urlencoded({ extended: true, limit: '10mb' }));

// Serve static project assets (from public/projects)
// This ensures assets generated by PrototypeAssetGenerator are accessible
// path: server/src/index.ts -> ../../public/projects
app.use('/projects', express.static(path.join(__dirname, '../../public/projects')));

// Serve CUA video recordings (from public/cua-recordings)
app.use('/cua-recordings', express.static(path.join(__dirname, '../../public/cua-recordings')));

// Offline Mode Middleware - specific for handling DB disconnects
app.use(offlineModeMiddleware);

// Request timeout middleware (60 seconds default for most routes)
// P0 FIX: Reduced from 20 minutes to 60 seconds - LLM routes override as needed
app.use(requestTimeout(60000)); // 60 seconds default

// Force JSON responses for all API routes (must be before routes)
app.use(forceJsonResponse);

// API Versioning middleware (must be before routes)
app.use(apiVersioning);

// Performance monitoring middleware (track all requests)
app.use(performanceMonitor);

// Swagger/OpenAPI documentation
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec, {
  customCss: '.swagger-ui .topbar { display: none }',
  customSiteTitle: 'ORBITAI API Documentation',
}));

// Maintenance mode middleware (before routes)
app.use(maintenanceModeMiddleware);

// Health check (before rate limiting)
app.get('/health', (_req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// Register routes via auto-loader
await loadRoutes(app);

// 404 handler for API routes (must be before error handler)
app.use('/api/*', (req, res) => {
  res.setHeader('Content-Type', 'application/json');
  res.status(404).json({
    success: false,
    error: {
      message: `API endpoint not found: ${req.method} ${req.originalUrl}`
    }
  });
});

// Error handling middleware (must be last)
app.use(errorHandler);

// Startup timing helper
const startupTimings: { name: string; duration: number }[] = [];
const startupStart = Date.now();

function trackTiming(name: string, startTime: number) {
  const duration = Date.now() - startTime;
  startupTimings.push({ name, duration });
  return duration;
}

// Start server with optimized parallel initialization
async function startServer() {
  const serverStartTime = Date.now();

  try {
    // PHASE 1: Critical path - Database connection (required for everything)
    const dbStart = Date.now();
    logger.info(`Connecting to MongoDB at: ${config.mongodbUri.replace(/:([^:@]+)@/, ':****@')}`); // Mask password
    await connectDatabase();
    trackTiming('Database connection', dbStart);
    logger.info('Database connected successfully');

    // PHASE 2: Start HTTP server IMMEDIATELY after DB (accept connections early)
    // Initialize WebSocket service
    webSocketService.initialize(httpServer);

    // Connect GenerationStatus service to WebSocket for real-time Mission Control updates
    const { generationStatusService } = await import('./services/GenerationStatus.service.js');
    generationStatusService.setSocketEmitter(webSocketService.getGenerationStatusEmitter());
    logger.info('[GenerationStatus] Real-time generation status enabled');

    // Initialize Voice WebSocket service (must be before httpServer.listen)
    const { voiceWebSocketService } = await import('./services/voiceWebSocket.service.js');
    voiceWebSocketService.initialize(httpServer);
    logger.info('[VoiceWebSocket] Voice WebSocket service initialized on /ws/voice');

    httpServer.listen(PORT, () => {
      const listenTime = Date.now() - serverStartTime;
      logger.info(`🚀 OrbitAI Backend Server running on port ${PORT} (${listenTime}ms)`);
      logger.info(`📡 Environment: ${config.nodeEnv}`);
    });

    // PHASE 3: Non-blocking parallel initialization (fire and forget)
    // These run in background and don't block server startup

    // Redis & Queue - non-blocking
    redisService.connect().catch((error: unknown) => {
      logger.warn('Redis initialization failed, continuing without cache:', toApiError(error).message);
    });

    queueService.initialize().catch((error: unknown) => {
      logger.warn('Queue service initialization failed, continuing without queues:', toApiError(error).message);
    });

    // PHASE 4: Parallel service initialization (all independent services at once)
    const parallelStart = Date.now();

    const parallelInitPromises = [
      // Feature flag service (important for app behavior)
      import('./services/featureFlagAdapter.js')
        .then(({ initializeFeatureFlags }) => initializeFeatureFlags())
        .then(() => logger.info('✅ Feature Flag Service initialized'))
        .catch((error) => logger.warn('Failed to initialize feature flag service:', error.message)),

      // LLM Router Settings
      import('./services/llmRouterSettings.service.js')
        .then(({ llmRouterSettingsService }) => llmRouterSettingsService.initializeDefaultSettings())
        .then(() => logger.info('✅ LLM Router Settings initialized'))
        .catch((error) => logger.warn('Failed to initialize LLM router settings:', error.message)),

      // Model Registry - Load models from database (including synced models)
      import('./services/llm/models/ModelRegistry.js')
        .then(async ({ modelRegistry }) => {
          await modelRegistry.initialize();
          logger.info('✅ Model Registry initialized from database');
          
          // Migrate environment keys to database AFTER ModelRegistry is initialized
          return import('./services/apiKeyManagement.service.js')
            .then(async ({ apiKeyManagement }) => {
              await apiKeyManagement.migrateEnvKeysToDb();
              logger.info('✅ Environment API keys migrated to database');
            });
        })
        .catch((error: unknown) => logger.warn('Failed to initialize model registry or migrate API keys:', toApiError(error).message)),

      // Model Sync Service - Load sync status and start monthly scheduler
      import('./services/modelSync.service.js')
        .then(async ({ modelSyncService }) => {
          // Load persisted sync status from database
          await modelSyncService.loadSyncStatus();
          // Start monthly scheduler
          modelSyncService.startMonthlySync();
          logger.info('✅ Model Sync monthly scheduler started');
        })
        .catch((error: unknown) => logger.warn('Failed to start model sync scheduler:', toApiError(error).message)),

      // Service imports (just verify they load, no initialization needed)
      import('./services/processMining.service.js')
        .then(() => logger.info('✅ Process Mining service ready'))
        .catch((error) => logger.warn('Process Mining service failed:', error.message)),

      import('./services/nlp.service.js')
        .then(() => logger.info('✅ NLP service ready'))
        .catch((error) => logger.warn('NLP service failed:', error.message)),

      import('./services/processAnalytics.service.js')
        .then(() => logger.info('✅ Process Analytics service ready'))
        .catch((error) => logger.warn('Process Analytics service failed:', error.message)),

      import('./services/workflowEngine.service.js')
        .then(() => logger.info('✅ Workflow Engine service ready'))
        .catch((error) => logger.warn('Workflow Engine service failed:', error.message)),

      import('./services/collaborativeWiki.service.js')
        .then(() => logger.info('✅ Collaborative Wiki service ready'))
        .catch((error) => logger.warn('Collaborative Wiki service failed:', error.message)),

      import('./services/aiOptimization.service.js')
        .then(() => logger.info('✅ AI Optimization service ready'))
        .catch((error) => logger.warn('AI Optimization service failed:', error.message)),

      import('./services/processSimulation.service.js')
        .then(() => logger.info('✅ Process Simulation service ready'))
        .catch((error) => logger.warn('Process Simulation service failed:', error.message)),

      import('./services/complianceAudit.service.js')
        .then(() => logger.info('✅ Compliance & Audit service ready'))
        .catch((error) => logger.warn('Compliance & Audit service failed:', error.message)),

      import('./services/communitySharing.service.js')
        .then(() => logger.info('✅ Community Sharing service ready'))
        .catch((error) => logger.warn('Community Sharing service failed:', error.message)),

      import('./services/processImprovement.service.js')
        .then(({ processImprovementService }) => {
          logger.info('✅ Process Improvement service ready');

          // First, cleanup any stuck improvements
          setTimeout(() => {
            processImprovementService.cleanupStuckImprovements(5).catch((error: unknown) => {
              logger.warn('Failed to cleanup stuck improvements:', toApiError(error).message);
            });
          }, 2000);

          // Defer assessment to after startup (with longer delay to allow cleanup)
          // Only assess truly pending improvements (not stuck ones)
          setTimeout(() => {
            processImprovementService.assessAllPendingImprovements().catch((error: any) => {
              logger.warn('Failed to assess pending improvements:', error.message);
            });
          }, 10000); // Increased delay to 10 seconds

          // Schedule periodic cleanup every 10 minutes to prevent stuck improvements
          setInterval(() => {
            processImprovementService.cleanupStuckImprovements(5).catch((error: any) => {
              logger.warn('Periodic cleanup of stuck improvements failed:', error.message);
            });
          }, 10 * 60 * 1000); // Every 10 minutes
        })
        .catch((error) => logger.warn('Process Improvement service failed:', error.message)),

      // Backup scheduler
      import('./services/backupScheduler.service.js')
        .then(({ backupScheduler }) => backupScheduler.start())
        .then(() => logger.info('✅ Backup scheduler initialized'))
        .catch((error) => logger.warn('Backup scheduler failed:', error.message)),
    ];

    // Wait for all parallel initializations
    await Promise.allSettled(parallelInitPromises);
    trackTiming('Parallel service init', parallelStart);

    // PHASE 5: Deferred initialization (non-critical, run after server is ready)
    setTimeout(async () => {
      // Check if DB is connected before running seeds to avoid race conditions
      if (mongoose.connection.readyState !== 1) {
        logger.warn('⚠️  Skipping deferred initialization steps - Database not connected');
        return;
      }

      const deferredStart = Date.now();

      // Agent Knowledge Aggregator - defer to avoid blocking startup
      try {
        const { agentKnowledgeAggregator } = await import('./services/agentKnowledgeAggregator.js');
        // Start with skipInitialRun to avoid immediate aggregation
        agentKnowledgeAggregator.start(1, true); // 1 hour interval, skip initial run
        logger.info('✅ Agent Knowledge Aggregator scheduled (runs every hour)');
      } catch (error) {
        logger.warn('Failed to start agent knowledge aggregator');
      }

      // Neo4j - optional, only initialize if configured
      if (process.env.NEO4J_URI) {
        try {
          const { neo4jService } = await import('./services/neo4j.service.js');
          await neo4jService.initialize();
          logger.info('✅ Neo4j Knowledge Graph service initialized');
        } catch (error: unknown) {
          logger.debug('Neo4j service skipped: ' + toApiError(error).message);
        }
      } else {
        logger.debug('Neo4j service skipped (NEO4J_URI not configured)');
      }

      // MCP health checks - defer to after startup
      try {
        const { mcpService } = await import('./services/mcp.service.js');
        const mcpHealth = await mcpService.checkAllSystemServersHealth();

        logger.info('\n📡 MCP Server Configuration Status:');
        mcpHealth.forEach(health => {
          const statusIcon = health.status === 'healthy' ? '✅' : health.status === 'degraded' ? '⚠️' : '❌';
          logger.info(`   ${statusIcon} ${health.name} (${health.serverId}): ${health.status.toUpperCase()}`);
        });

        mcpService.startHealthChecks(5 * 60 * 1000);
      } catch (error: unknown) {
        logger.warn('MCP health check failed:', toApiError(error).message);
      }

      // Seed operations - run in background, don't log failures prominently
      const seedPromises = [
        // import('./services/seedFeatureFlags.service.js').catch(() => { }), // File missing
        // import('./services/seedPackages.service.js').catch(() => { }), // File missing

        import('./services/seedHomepageContent.service.js')
          .then(({ seedHomepageContent }) => seedHomepageContent())
          .catch(() => { }),
        // import('./services/seedStandards.service.js').catch(() => { }), // File missing
        // import('./services/seedAgentKnowledge.service.js').catch(() => { }), // File missing
        // import('./services/ensureDefaultAdmin.service.js').catch(() => { }), // File missing
      ];

      await Promise.allSettled(seedPromises);
      trackTiming('Deferred initialization', deferredStart);

      // Log API key status
      try {
        const { apiKeyProvider } = await import('./services/apiKeyProvider.service.js');
        const geminiConfigured = await apiKeyProvider.hasApiKey('gemini');
        const geminiSource = await apiKeyProvider.getApiKeySource('gemini');
        const e2bConfigured = await apiKeyProvider.hasApiKey('e2b');
        const e2bSource = await apiKeyProvider.getApiKeySource('e2b');

        logger.info(`\n🔑 API Keys:`);
        logger.info(`   Gemini: ${geminiConfigured ? `✅ (${geminiSource})` : '❌ Not configured'}`);
        logger.info(`   E2B: ${e2bConfigured ? `✅ (${e2bSource})` : '❌ Not configured'}`);
      } catch { }

      // Print startup timing summary
      const totalTime = Date.now() - serverStartTime;
      logger.info(`\n⏱️  Startup Performance:`);
      startupTimings.forEach(t => logger.info(`   ${t.name}: ${t.duration}ms`));
      logger.info(`   Total startup time: ${totalTime}ms`);

    }, 100); // Small delay to let server start accepting connections first

  } catch (error: unknown) {
    logger.error('Failed to start server:', toApiError(error));
    process.exit(1);
  }
}

startServer();

export default app;


